// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weoyjqiarnzmwlknfpcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indlb3lqcWlhcm56bXdsa25mcGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDYzNzYsImV4cCI6MjA1MDE4MjM3Nn0.DiCQRrR8mueNsi-FNdfDYuwCRURAmeLpFJfQk6YmyH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);